import { QuestionPreviewCard } from './QuestionPreviewCard';

export function GameForm({
  gameTitle, setGameTitle,
  gameDescription, setGameDescription,
  gameCreator, setGameCreator,
  gameLanguage, setGameLanguage,
  gameCefrLevel, setGameCefrLevel,
  gameSubject, setGameSubject,
  error,
  loading,
  selectedGameForEdit,
  userInfo,
  currentUser,
  availableSubjects,
  availableCefrLevels,
  availableLanguages,
  showCefrTips,
  setShowCefrTips,
  previewQuestions,
  previewLoading,
  onSubmit,
  onCancel,
  onAddQuestion,
  onEditQuestion,
  onDeleteQuestion,
  onGenerate,
  onImport
}) {
  return (
    <div className="app-container">
      <div className="panel panel-large animate-join-focus" style={{ textAlign: 'left' }}>
        <div style={{ marginBottom: 24 }}>
          <h2>{selectedGameForEdit ? 'Edit Dahoot Details' : 'Create New Dahoot'}</h2>
          <p style={{ color: 'var(--text-secondary)', margin: 0 }}>
            Specify the details and metadata tags for your Dahoot.
          </p>
        </div>

        {error && (
          <div style={{
            background: 'rgba(239, 68, 68, 0.1)',
            border: '1px solid rgba(239, 68, 68, 0.3)',
            color: '#ff4b60',
            padding: '12px 16px',
            borderRadius: '8px',
            marginBottom: 20
          }}>
            {error}
          </div>
        )}

        <form onSubmit={onSubmit}>
          <div className="form-group">
            <label className="form-label">Game Title *</label>
            <input
              type="text"
              className="form-input"
              placeholder="e.g. World History Trivia"
              value={gameTitle}
              onChange={(e) => setGameTitle(e.target.value)}
              disabled={loading}
              autoFocus
              required
            />
          </div>

          <div className="form-group">
            <label className="form-label">Description (optional / autogenerated)</label>
            <textarea
              className="form-input"
              placeholder="e.g. 10 questions covering major historical events of the 20th century. (Leave blank, if using AI to generate questions.)"
              value={gameDescription}
              onChange={(e) => setGameDescription(e.target.value)}
              disabled={loading}
              rows={3}
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
            <div className="form-group">
              <label className="form-label">Creator / Author *</label>
              <select
                className="form-input"
                value={gameCreator}
                onChange={(e) => setGameCreator(e.target.value)}
                disabled={loading}
                style={{ cursor: 'pointer' }}
                required
              >
                {Array.from(new Set([
                  gameCreator,
                  userInfo?.dahoot_username,
                  currentUser?.name,
                  currentUser?.email
                ].filter(Boolean))).map(opt => (
                  <option key={opt} value={opt}>{opt}</option>
                ))}
              </select>
            </div>

            <div className="form-group">
              <label className="form-label">Language *</label>
              <select
                className="form-input"
                value={gameLanguage}
                onChange={(e) => setGameLanguage(e.target.value)}
                disabled={loading}
                style={{ cursor: 'pointer' }}
                required
              >
                <option value="">Select Language...</option>
                {availableLanguages.map(lang => (
                  <option key={lang} value={lang}>{lang}</option>
                ))}
              </select>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
            <div className="form-group">
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <label className="form-label">CEFR Language Level *</label>
                <button
                  type="button"
                  onClick={() => setShowCefrTips(!showCefrTips)}
                  style={{
                    background: 'none',
                    border: 'none',
                    color: 'var(--text-secondary)',
                    fontSize: '0.75rem',
                    cursor: 'pointer',
                    textDecoration: 'underline',
                    fontWeight: 600,
                    display: 'flex',
                    alignItems: 'center',
                    gap: '3px',
                    padding: '2px'
                  }}
                >
                  💡 Quick Guide
                </button>
              </div>
              <select
                className="form-input"
                value={gameCefrLevel}
                onChange={(e) => setGameCefrLevel(e.target.value)}
                disabled={loading}
                style={{ cursor: 'pointer' }}
                required
              >
                <option value="">Select CEFR Level...</option>
                {availableCefrLevels.map(lvl => (
                  <option key={lvl} value={lvl}>{lvl}</option>
                ))}
              </select>

              {showCefrTips && (
                <div className="animate-fade-in text-[11px] text-slate-500 bg-slate-50 border border-slate-200/50 rounded-xl p-3 mt-2 space-y-1.5 leading-normal">
                  <div><strong>A1 (Beginner)</strong> / <strong>A2 (Elementary)</strong>: Simple everyday sentences, basic questions.</div>
                  <div><strong>B1 (Intermediate)</strong> / <strong>B2 (Upper-Intermediate)</strong>: Spontaneous conversation, clear texts on familiar topics.</div>
                  <div><strong>C1 (Advanced)</strong> / <strong>C2 (Mastery)</strong>: Complex subjects, professional or academic level fluency.</div>
                </div>
              )}
            </div>

            <div className="form-group">
              <label className="form-label">Subject *</label>
              <select
                className="form-input"
                value={gameSubject}
                onChange={(e) => setGameSubject(e.target.value)}
                disabled={loading}
                style={{ cursor: 'pointer' }}
                required
              >
                <option value="">Select Subject...</option>
                {availableSubjects.map(sub => (
                  <option key={sub} value={sub}>{sub}</option>
                ))}
              </select>
            </div>
          </div>

          {/* Questions Section */}
          <div style={{
            marginTop: '32px',
            borderTop: '1px dashed rgba(93, 107, 130, 0.2)',
            paddingTop: '24px'
          }}>
            <div className="flex justify-between items-center mb-4" style={{ textAlign: 'left' }}>
              <div>
                <h3 style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--text-secondary)', margin: 0 }}>
                  Questions ({previewQuestions.length})
                </h3>
                <p style={{ color: 'var(--text-muted)', fontSize: '0.85rem', margin: '4px 0 0 0' }}>
                  Add, edit, or remove questions. Changes are saved immediately.
                </p>
              </div>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={onAddQuestion}
                  className="flex items-center gap-1.5 px-3 py-2 text-sm font-semibold text-emerald-700 hover:text-emerald-800 bg-emerald-50 hover:bg-emerald-100 border border-emerald-200 rounded-xl transition-colors cursor-pointer shrink-0"
                >
                  ➕ Add Question
                </button>
                <button
                  type="button"
                  onClick={onGenerate}
                  className="flex items-center gap-1.5 px-3 py-2 text-sm font-semibold text-amber-700 hover:text-amber-800 bg-amber-50 hover:bg-amber-100 border border-amber-200 rounded-xl transition-colors cursor-pointer shrink-0"
                  title="Autogenerate questions using AI"
                >
                  ✨ Autogenerate
                </button>
                <button
                  type="button"
                  onClick={onImport}
                  className="flex items-center gap-1.5 px-3 py-2 text-sm font-semibold text-violet-700 hover:text-violet-800 bg-violet-50 hover:bg-violet-100 border border-violet-200 rounded-xl transition-colors cursor-pointer shrink-0"
                >
                  📥 Import
                </button>
              </div>
            </div>

            {previewLoading ? (
              <div style={{ textAlign: 'center', padding: '40px' }}>
                <div className="spinner" style={{ margin: '0 auto 16px auto' }} />
                <p style={{ color: 'var(--text-secondary)' }}>Loading questions...</p>
              </div>
            ) : previewQuestions.length === 0 ? (
              <div style={{
                textAlign: 'center',
                padding: '32px 16px',
                background: 'rgba(93, 107, 130, 0.02)',
                border: '1px dashed rgba(93, 107, 130, 0.15)',
                borderRadius: 'var(--radius-md)',
                color: 'var(--text-muted)'
              }}>
                No questions yet. Click <strong>➕ Add Question</strong> to get started.
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mt-4">
                {previewQuestions.map((question, qIdx) => (
                  <QuestionPreviewCard
                    key={question.id}
                    question={question}
                    index={qIdx}
                    canEdit={true}
                    onEdit={onEditQuestion}
                    onDelete={onDeleteQuestion}
                  />
                ))}
              </div>
            )}
          </div>

          <div style={{ display: 'flex', gap: 12, justifyContent: 'flex-end', marginTop: 24 }}>
            <button type="button" className="btn btn-secondary" onClick={onCancel} disabled={loading} style={{ width: 'auto', minWidth: 120 }}>
              Cancel
            </button>
            <button type="submit" className="btn btn-primary" disabled={loading} style={{ width: 'auto', minWidth: 150 }}>
              {loading ? 'Saving...' : 'Save Game'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
